import type { Metadata } from "next";
import { Manrope } from 'next/font/google';
import "./globals.css";
import { Providers } from "@/store/provider";
import { ThemeWrapper } from "@/components/ThemeWrapper";
import ThemeHydrator from "@/components/ThemeHydrator";


const manrope = Manrope({
  variable: '--font-manrope',
  subsets: ['latin'],
  weight: ['400', '500', '600', '700'], // Optional: choose the weights you need
});


export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" >
      <body
        className={`${manrope.variable} antialiased`}
      >
        <Providers>
          <ThemeHydrator />
          <ThemeWrapper>
            {children}
          </ThemeWrapper>
        </Providers>
      </body>
    </html>
  );
}
